/*
 * C++ wrapper for CuTeDSL-exported persistent GEMM kernels (gemm_output).
 *
 * Links against .o files exported by CuTeDSL's export_to_c(), providing
 * CuTeDSL kernel performance with zero Python dispatch overhead.
 *
 * Round 46: fwd and dgrad are exported with is_dynamic_layout=False — shapes
 * and strides baked into the kernel binary.  Tensor descriptor is just
 * { void *data; }.
 * Round 48: wgrad also switched to is_dynamic_layout=False.  gemm_fc1 R46
 * found wgrad regressed with static layout at M=4096, but gemm_output wgrad
 * has M=73472 — the larger descriptor-fill overhead makes static layout
 * net-positive here.  All three directions now use { void *data; } only.
 *
 * Directions:
 *   fwd:   C[M,N]   = A[M,K]   * B[N,K]    BF16→BF16   (all row-major, STATIC)
 *   dgrad: C[M,N]   = A[M,K]   * B[N,K]    BF16→BF16   (A row-major, B col-major view of W_padded, C row-major, STATIC)
 *   wgrad: C[M,N]   = A[M,K]   * B[N,K]    BF16→FP32   (A col-major view of dY, B col-major view of X, C row-major FP32, STATIC since R48)
 */

#include <torch/extension.h>
#include <c10/cuda/CUDAStream.h>
#include <cuda_runtime.h>
#include <cstdlib>

#include "gemm_output_fwd.h"
#include "gemm_output_dgrad.h"
#include "gemm_output_wgrad.h"

// CuTeDSL >= 4.4 renamed the C ABI generated by export_to_c():
//   _Kernel_Metadata_t  -> _Kernel_Module_t
//   _Kernel_Metadata_Load -> _Kernel_Module_Load
//   <op>_wrapper        -> cute_dsl_<op>_wrapper
// Older versions (<= 4.3) still emit the original names. Keep a single source
// of truth here that maps the old aliases to the new ones when needed.
#if !defined(GEMM_OUTPUT_USE_LEGACY_CUTEDSL_ABI)
#define GEMM_OUTPUT_KERNEL_T(op)         op##_Kernel_Module_t
#define GEMM_OUTPUT_KERNEL_LOAD(op)      op##_Kernel_Module_Load
#define GEMM_OUTPUT_KERNEL_WRAPPER(op)   cute_dsl_##op##_wrapper
#else
#define GEMM_OUTPUT_KERNEL_T(op)         op##_Kernel_Metadata_t
#define GEMM_OUTPUT_KERNEL_LOAD(op)      op##_Kernel_Metadata_Load
#define GEMM_OUTPUT_KERNEL_WRAPPER(op)   op##_wrapper
#endif

static bool g_initialized = false;
static GEMM_OUTPUT_KERNEL_T(gemm_output_fwd)   g_fwd_module;
static GEMM_OUTPUT_KERNEL_T(gemm_output_dgrad) g_dgrad_module;
static GEMM_OUTPUT_KERNEL_T(gemm_output_wgrad) g_wgrad_module;

static void ensure_init() {
    if (!g_initialized) {
        GEMM_OUTPUT_KERNEL_LOAD(gemm_output_fwd)(&g_fwd_module);
        GEMM_OUTPUT_KERNEL_LOAD(gemm_output_dgrad)(&g_dgrad_module);
        GEMM_OUTPUT_KERNEL_LOAD(gemm_output_wgrad)(&g_wgrad_module);
        g_initialized = true;
    }
}

/* ---------- fwd: logits = X @ W_padded^T ----------
 * Round 46: is_dynamic_layout=False — shapes baked into kernel binary.
 * Descriptor is just { void *data; }.
 *
 * Shapes locked by export_kernels.py:
 *   X[40960, 1024]       BF16 row-major → A
 *   W_padded[73472, 1024] BF16 row-major → B
 *   out[40960, 73472]     BF16 row-major → C
 */
void cutedsl_gemm_fwd(torch::Tensor x, torch::Tensor w, torch::Tensor out) {
    ensure_init();
    TORCH_CHECK(x.size(0) == 40960 && x.size(1) == 1024,
                "fwd: expected X[40960,1024], got [", x.size(0), ",", x.size(1), "]");
    TORCH_CHECK(w.size(0) == 73472 && w.size(1) == 1024,
                "fwd: expected W[73472,1024], got [", w.size(0), ",", w.size(1), "]");
    TORCH_CHECK(out.size(0) == 40960 && out.size(1) == 73472,
                "fwd: expected out[40960,73472], got [", out.size(0), ",", out.size(1), "]");

    gemm_output_fwd_Tensor_a_t a = { x.data_ptr() };
    gemm_output_fwd_Tensor_b_t b = { w.data_ptr() };
    gemm_output_fwd_Tensor_c_t c = { out.data_ptr() };

    auto stream = c10::cuda::getCurrentCUDAStream().stream();
    int32_t ret = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_fwd)(&g_fwd_module, &a, &b, &c, stream);
    TORCH_CHECK(ret == 0, "CuTeDSL gemm_output fwd failed: ", ret);
}

/* ---------- dgrad: dX = dY @ W_padded ----------
 * Round 46: is_dynamic_layout=False — shapes baked into kernel binary.
 * B is compiled with b_col_major=True: the col-major strides of the
 * W_padded view are baked in.  Caller passes W_padded (row-major
 * [73472, 1024]) and the kernel interprets it as col-major B[1024, 73472].
 *
 * Shapes locked by export_kernels.py:
 *   dY[40960, 73472]     BF16 row-major → A
 *   W_padded[73472, 1024] BF16 row-major → B (col-major view baked)
 *   dX[40960, 1024]       BF16 row-major → C
 */
void cutedsl_gemm_dgrad(torch::Tensor dy, torch::Tensor w_padded, torch::Tensor dx) {
    ensure_init();
    TORCH_CHECK(dy.size(0) == 40960 && dy.size(1) == 73472,
                "dgrad: expected dY[40960,73472], got [", dy.size(0), ",", dy.size(1), "]");
    TORCH_CHECK(w_padded.size(0) == 73472 && w_padded.size(1) == 1024,
                "dgrad: expected W_padded[73472,1024], got [", w_padded.size(0), ",", w_padded.size(1), "]");
    TORCH_CHECK(dx.size(0) == 40960 && dx.size(1) == 1024,
                "dgrad: expected dX[40960,1024], got [", dx.size(0), ",", dx.size(1), "]");

    gemm_output_dgrad_Tensor_a_t a = { dy.data_ptr() };
    gemm_output_dgrad_Tensor_b_t b = { w_padded.data_ptr() };
    gemm_output_dgrad_Tensor_c_t c = { dx.data_ptr() };

    auto stream = c10::cuda::getCurrentCUDAStream().stream();
    int32_t ret = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_dgrad)(&g_dgrad_module, &a, &b, &c, stream);
    TORCH_CHECK(ret == 0, "CuTeDSL gemm_output dgrad failed: ", ret);
}

/* ---------- wgrad: dW = dY^T @ X (with B col-major view of X) ----------
 * Round 48: is_dynamic_layout=False — shapes baked into kernel binary.
 * Descriptor is just { void *data; } for all three tensors.
 *
 * dY[K_act=40960, M_w=73472] row-major → kernel sees col-major A[73472, 40960]
 * X[K_act=40960, N=1024]     row-major → kernel sees col-major B[1024, 40960]
 * dW[M_w=73472, N=1024]      FP32 row-major → C
 *
 * Shapes locked by export_kernels.py (M=73472, N=1024, K=40960).
 */
void cutedsl_gemm_wgrad(torch::Tensor dy, torch::Tensor x, torch::Tensor dw) {
    ensure_init();
    TORCH_CHECK(dy.size(0) == 40960 && dy.size(1) == 73472,
                "wgrad: expected dY[40960,73472], got [", dy.size(0), ",", dy.size(1), "]");
    TORCH_CHECK(x.size(0) == 40960 && x.size(1) == 1024,
                "wgrad: expected X[40960,1024], got [", x.size(0), ",", x.size(1), "]");
    TORCH_CHECK(dw.size(0) == 73472 && dw.size(1) == 1024,
                "wgrad: expected dW[73472,1024], got [", dw.size(0), ",", dw.size(1), "]");

    gemm_output_wgrad_Tensor_a_t a = { dy.data_ptr() };
    gemm_output_wgrad_Tensor_b_t b = { x.data_ptr() };
    gemm_output_wgrad_Tensor_c_t c = { dw.data_ptr() };

    auto stream = c10::cuda::getCurrentCUDAStream().stream();
    int32_t ret = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_wgrad)(&g_wgrad_module, &a, &b, &c, stream);
    TORCH_CHECK(ret == 0, "CuTeDSL gemm_output wgrad failed: ", ret);
}

/* ---------- combined bwd: dgrad + wgrad in one C++ dispatch ----------
 * Saves one Python→C++ transition (~0.1ms pybind11 overhead).
 *
 * x is [K_act, N=1024] row-major; passed directly as a col-major B view
 * to wgrad (b_col_major=True kernel) — no copy needed.
 *
 * Optional GEMM_OUTPUT_BWD_PARALLEL_STREAMS=1 launches dgrad & wgrad on
 * separate CUDA streams, joined back into the current stream via events.
 * Persistent CTAs saturate SMs, but launch / scheduler / TMA-fetch overlap
 * still trims a few µs per call when both kernels are in flight.
 */

static cudaStream_t g_bwd_aux_stream = nullptr;
static cudaEvent_t  g_bwd_dy_ready_event = nullptr;
static cudaEvent_t  g_bwd_aux_done_event = nullptr;
static bool         g_bwd_parallel_init = false;

static void ensure_bwd_parallel_init() {
    if (!g_bwd_parallel_init) {
        cudaStreamCreateWithPriority(&g_bwd_aux_stream, cudaStreamNonBlocking, 0);
        cudaEventCreateWithFlags(&g_bwd_dy_ready_event, cudaEventDisableTiming);
        cudaEventCreateWithFlags(&g_bwd_aux_done_event, cudaEventDisableTiming);
        g_bwd_parallel_init = true;
    }
}

static bool bwd_parallel_streams_enabled() {
    static int v = -1;
    if (v < 0) {
        const char *e = std::getenv("GEMM_OUTPUT_BWD_PARALLEL_STREAMS");
        v = (e != nullptr && std::atoi(e) != 0) ? 1 : 0;
    }
    return v != 0;
}

void cutedsl_gemm_bwd(torch::Tensor dy, torch::Tensor w_padded, torch::Tensor dx,
                      torch::Tensor x, torch::Tensor dw) {
    ensure_init();

    // --- dgrad (Round 46: static layout — descriptor is { void* } only) ---
    gemm_output_dgrad_Tensor_a_t a_dg = { dy.data_ptr() };
    gemm_output_dgrad_Tensor_b_t b_dg = { w_padded.data_ptr() };
    gemm_output_dgrad_Tensor_c_t c_dg = { dx.data_ptr() };

    // --- wgrad (Round 48: static layout — descriptor is { void* } only) ---
    gemm_output_wgrad_Tensor_a_t a_wg = { dy.data_ptr() };
    gemm_output_wgrad_Tensor_b_t b_wg = { x.data_ptr() };
    gemm_output_wgrad_Tensor_c_t c_wg = { dw.data_ptr() };

    auto cur_stream = c10::cuda::getCurrentCUDAStream().stream();

    if (bwd_parallel_streams_enabled()) {
        ensure_bwd_parallel_init();
        // Make sure the producer of dy/x/b_dgrad on the current stream is done
        // (all previous work on cur_stream visible to aux stream).
        cudaEventRecord(g_bwd_dy_ready_event, cur_stream);
        cudaStreamWaitEvent(g_bwd_aux_stream, g_bwd_dy_ready_event, 0);

        // Launch wgrad on aux stream (it's the heavier of the two on M=4096),
        // dgrad on current stream — symmetric work distribution.
        int32_t ret_wg = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_wgrad)(
            &g_wgrad_module, &a_wg, &b_wg, &c_wg, g_bwd_aux_stream);
        TORCH_CHECK(ret_wg == 0, "CuTeDSL gemm_output wgrad failed: ", ret_wg);
        int32_t ret_dg = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_dgrad)(
            &g_dgrad_module, &a_dg, &b_dg, &c_dg, cur_stream);
        TORCH_CHECK(ret_dg == 0, "CuTeDSL gemm_output dgrad failed: ", ret_dg);

        // Join aux stream back into current stream.
        cudaEventRecord(g_bwd_aux_done_event, g_bwd_aux_stream);
        cudaStreamWaitEvent(cur_stream, g_bwd_aux_done_event, 0);
    } else {
        int32_t ret_dg = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_dgrad)(
            &g_dgrad_module, &a_dg, &b_dg, &c_dg, cur_stream);
        TORCH_CHECK(ret_dg == 0, "CuTeDSL gemm_output dgrad failed: ", ret_dg);
        int32_t ret_wg = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_wgrad)(
            &g_wgrad_module, &a_wg, &b_wg, &c_wg, cur_stream);
        TORCH_CHECK(ret_wg == 0, "CuTeDSL gemm_output wgrad failed: ", ret_wg);
    }
}

/* ============================================================================
 * Round 45: "_fast" wrappers that fold .contiguous() / .reshape() /
 * torch.empty() / weight-padding / .as_strided() into a single pybind11 call.
 *
 * Mirrors gemm_fc1 R37/R39 architecture: accept the upstream 3-D tensors
 * directly, make them contiguous + 2-D internally via ATen C++ APIs (no Python
 * dispatch), manage the padded-weight cache in C++, allocate output tensors,
 * dispatch the exported CuTeDSL kernels, and return properly shaped results.
 *
 * Saves ~5-12 µs/call of Python dispatch overhead (.contiguous, .view,
 * torch.empty, _ensure_w_cache, .as_strided, .view_as, .slice) which the R44
 * wrapper probe identified as ~17 µs of which ~half is Python-side ATen calls.
 * ============================================================================ */

static constexpr int64_t GEMM_PAD_TO = 128;
static torch::Tensor g_w_padded_cache;
static int64_t g_w_padded_orig_n = 0;

static void ensure_w_cache_cpp(torch::Tensor weight) {
    int64_t orig_n = weight.size(0);
    int64_t K = weight.size(1);
    int64_t padded_n = (orig_n + GEMM_PAD_TO - 1) / GEMM_PAD_TO * GEMM_PAD_TO;

    if (!g_w_padded_cache.defined() ||
        g_w_padded_cache.size(0) != padded_n ||
        g_w_padded_cache.size(1) != K ||
        g_w_padded_cache.dtype() != weight.dtype() ||
        g_w_padded_cache.device() != weight.device()) {
        g_w_padded_cache = torch::zeros({padded_n, K}, weight.options());
    }

    if (padded_n == orig_n) {
        g_w_padded_cache.copy_(weight);
    } else {
        g_w_padded_cache.slice(/*dim=*/0, /*start=*/0, /*end=*/orig_n).copy_(weight);
    }
    g_w_padded_orig_n = orig_n;
}

torch::Tensor cutedsl_gemm_fwd_fast(torch::Tensor x, torch::Tensor weight) {
    ensure_init();
    TORCH_CHECK(x.is_cuda() && weight.is_cuda());
    TORCH_CHECK(x.dtype() == torch::kBFloat16 && weight.dtype() == torch::kBFloat16);

    auto x_c = x.contiguous();
    int64_t K = x_c.size(-1);
    int64_t M = x_c.numel() / K;

    ensure_w_cache_cpp(weight);
    int64_t N = g_w_padded_cache.size(0);
    int64_t orig_n = g_w_padded_orig_n;

    TORCH_CHECK(M == 40960 && K == 1024 && N == 73472,
                "fwd_fast: expected M=40960 K=1024 N=73472; got M=",
                M, " K=", K, " N=", N);

    auto out = torch::empty({M, N}, x_c.options());

    // Round 46: static layout — descriptor is { void* } only
    gemm_output_fwd_Tensor_a_t a = { x_c.data_ptr() };
    gemm_output_fwd_Tensor_b_t b = { g_w_padded_cache.data_ptr() };
    gemm_output_fwd_Tensor_c_t c = { out.data_ptr() };

    auto stream = c10::cuda::getCurrentCUDAStream().stream();
    int32_t ret = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_fwd)(
        &g_fwd_module, &a, &b, &c, stream);
    TORCH_CHECK(ret == 0, "CuTeDSL gemm_output fwd_fast failed: ", ret);

    /* Build as-strided view: preserve x's leading dims, last dim = orig_n,
     * but underlying row stride = N (padded).  Works for any ndim >= 1. */
    auto sizes_out = x.sizes().vec();
    sizes_out.back() = orig_n;
    std::vector<int64_t> strides_out(sizes_out.size());
    strides_out.back() = 1;
    if (sizes_out.size() >= 2) {
        strides_out[sizes_out.size() - 2] = N;
        for (int64_t i = (int64_t)sizes_out.size() - 3; i >= 0; --i) {
            strides_out[i] = strides_out[i + 1] * sizes_out[i + 1];
        }
    }
    return torch::as_strided(out, sizes_out, strides_out, /*offset=*/0);
}

std::tuple<torch::Tensor, torch::Tensor>
cutedsl_gemm_bwd_fast(torch::Tensor d_output, torch::Tensor x,
                      torch::Tensor weight) {
    ensure_init();
    TORCH_CHECK(d_output.is_cuda() && x.is_cuda() && weight.is_cuda());
    TORCH_CHECK(d_output.dtype() == torch::kBFloat16 &&
                x.dtype() == torch::kBFloat16 &&
                weight.dtype() == torch::kBFloat16);

    auto dy_c = d_output.contiguous();
    auto x_c  = x.contiguous();

    int64_t K_dy = dy_c.size(-1);
    int64_t M    = dy_c.numel() / K_dy;
    int64_t K_x  = x_c.size(-1);

    ensure_w_cache_cpp(weight);
    int64_t orig_n = g_w_padded_orig_n;
    int64_t N_pad  = g_w_padded_cache.size(0);

    auto d_input        = torch::empty(x_c.sizes(), x_c.options());
    auto d_weight_full  = torch::empty({N_pad, K_x},
                                       dy_c.options().dtype(torch::kFloat32));

    /* --- dgrad: dX = dY @ W_padded (Round 46: static layout, { void* } only) --- */
    gemm_output_dgrad_Tensor_a_t a_dg = { dy_c.data_ptr() };
    gemm_output_dgrad_Tensor_b_t b_dg = { g_w_padded_cache.data_ptr() };
    gemm_output_dgrad_Tensor_c_t c_dg = { d_input.data_ptr() };

    /* --- wgrad (Round 48: static layout — descriptor is { void* } only) --- */
    gemm_output_wgrad_Tensor_a_t a_wg = { dy_c.data_ptr() };
    gemm_output_wgrad_Tensor_b_t b_wg = { x_c.data_ptr() };
    gemm_output_wgrad_Tensor_c_t c_wg = { d_weight_full.data_ptr() };

    auto cur_stream = c10::cuda::getCurrentCUDAStream().stream();

    if (bwd_parallel_streams_enabled()) {
        ensure_bwd_parallel_init();
        cudaEventRecord(g_bwd_dy_ready_event, cur_stream);
        cudaStreamWaitEvent(g_bwd_aux_stream, g_bwd_dy_ready_event, 0);

        int32_t ret_wg = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_wgrad)(
            &g_wgrad_module, &a_wg, &b_wg, &c_wg, g_bwd_aux_stream);
        TORCH_CHECK(ret_wg == 0, "CuTeDSL gemm_output wgrad failed: ", ret_wg);
        int32_t ret_dg = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_dgrad)(
            &g_dgrad_module, &a_dg, &b_dg, &c_dg, cur_stream);
        TORCH_CHECK(ret_dg == 0, "CuTeDSL gemm_output dgrad failed: ", ret_dg);

        cudaEventRecord(g_bwd_aux_done_event, g_bwd_aux_stream);
        cudaStreamWaitEvent(cur_stream, g_bwd_aux_done_event, 0);
    } else {
        int32_t ret_dg = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_dgrad)(
            &g_dgrad_module, &a_dg, &b_dg, &c_dg, cur_stream);
        TORCH_CHECK(ret_dg == 0, "CuTeDSL gemm_output dgrad failed: ", ret_dg);
        int32_t ret_wg = GEMM_OUTPUT_KERNEL_WRAPPER(gemm_output_wgrad)(
            &g_wgrad_module, &a_wg, &b_wg, &c_wg, cur_stream);
        TORCH_CHECK(ret_wg == 0, "CuTeDSL gemm_output wgrad failed: ", ret_wg);
    }

    auto d_weight = d_weight_full.slice(/*dim=*/0, /*start=*/0, /*end=*/orig_n);
    return std::make_tuple(d_input, d_weight);
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("gemm_fwd",   &cutedsl_gemm_fwd,   "CuTeDSL gemm_output fwd");
    m.def("gemm_dgrad", &cutedsl_gemm_dgrad, "CuTeDSL gemm_output dgrad");
    m.def("gemm_wgrad", &cutedsl_gemm_wgrad, "CuTeDSL gemm_output wgrad FP32");
    m.def("gemm_bwd",   &cutedsl_gemm_bwd,   "CuTeDSL gemm_output combined dgrad+wgrad");
    m.def("gemm_fwd_fast",  &cutedsl_gemm_fwd_fast,
          "CuTeDSL gemm_output fwd (3-D in, internal weight-pad + alloc)");
    m.def("gemm_bwd_fast",  &cutedsl_gemm_bwd_fast,
          "CuTeDSL gemm_output combined dgrad+wgrad "
          "(3-D in, internal weight-pad + alloc, returns (d_input, d_weight))");
}
